
POST http://localhost:3000/api/auth/login
Content-Type : application/json

{
    "email" : "bhanu@gmail.com",
    "password" : "bhanu@1234"
}

POST http://localhost:3000/api/auth/signup
Content-Type : application/json

{   "name" : "rahul",
    "email" : "rahul@gmail.com",
    "password" : "rahul@1234"
}

GET http://localhost:3000/users